name: Test

on:
  push:
    branches:
      - main
jobs:
  download:
    name: download
    runs-on: ubuntu-latest
    
    steps:
    - name: install jq
      run: sudo apt-get install jq
    - name: artifact-id
      id: artifact-id
      run: |
        ARTIFACTS_URL="https://api.github.com/repos/upload-artifact/actions/runs/github.event.workflow_run.id/artifacts"
        RESPONSE=$(curl -H "Authorization: token ${{ secrets.GIT_TOKEN }}" $ARTIFACTS_URL)
        ARTIFACT_ID=$(echo $RESPONSE | jq -r '.artifacts[0].id')
        echo "ARTIFACT ID: $ARTIFACT_ID"
        echo "::set-output name=artifact_id::$ARTIFACT_ID"
      # env: 
      #  GITHUB_TOKEN: ${{ github.token }} 
      #  MYID: ${{ steps.artifact-id-step.outputs.artifact-id }}
      #  MYURL: ${{ steps.artifact-id-step.outputs.artifact-url }}   
    
    - name: Download
      run: |
        curl -L -o artifact.zip -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \ "https://api.github.com/repos/upload-artifact/actions/artifacts/1333217032/zip"
        
      
     
