name: Download Artifact

on: 
  workflow_dispatch 

jobs: 
  download-artifact: 
    runs-on: ubuntu-latest 
    steps: # Checkout is not strictly necessary for the API calls, but included for completeness 
    - name: Checkout code 
      uses: actions/checkout@v3 

    - name: List Artifacts for a Specific Workflow Run
      id: list-artifacts 
      run: | 
        ARTIFACTS_URL="https://api.github.com/repos/ {{ github.repository }}/actions/runs/{{ github.event.workflow_run.id }}/artifacts"
        ARTIFACTS_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "$ARTIFACTS_URL") 
        ARTIFACT_ID=$(echo "$ARTIFACTS_RESPONSE" | jq '.artifacts[] | select(.name=="YOUR_ARTIFACT_NAME_HERE").id') 
        echo "::set-output name=artifact_id::$ARTIFACT_ID" 
        fail_on_error: true

    - name: Download the Artifact 
      if: steps.list-artifacts.outputs.artifact_id 
      run: | 
        DOWNLOAD_URL="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.list-artifacts.outputs.artifact_id }}/zip" # The -L flag allows curl to follow redirects 
        curl -L -o YOUR_ARTIFACT_NAME_HERE.zip -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$DOWNLOAD_URL"
